; PlatformIO build settings.
; - Targets the Arduino Mega 2560.
; - Loads the CanControl library.
; - Builds one test program per environment.
; - Sets the serial monitor speed for each environment.

; Shared settings for all test environments
[env]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

lib_deps =
    willguimont/CanControl@^1.2.1

[env:motor_test]
build_src_filter =
    +<motor_run_test.cpp>

[env:actuation_test]
monitor_speed = 57600
build_src_filter =
    +<actuation_test.cpp>

[env:pt_test]
build_src_filter =
    +<pt_test.cpp>

[env:dwell_test]
monitor_speed = 57600
build_src_filter =
    +<dwell_csv_test.cpp>

[env:dwell_soak]
monitor_speed = 57600
build_src_filter =
    +<dwell_soak_test.cpp>



[env:cda_characterization]
monitor_speed = 57600
build_src_filter =
    +<cda_characterization_test.cpp>
